"use client"

import { UseFormReturn } from "react-hook-form"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"
import { CreateCallSheetData, UpdateCallSheetData } from "@/lib/validations/call-sheet"
import { CallSheetWithRelations } from "@/lib/types/database"

interface PreviewTabProps {
  form: UseFormReturn<CreateCallSheetData | UpdateCallSheetData>
  callSheet?: CallSheetWithRelations
}

export function PreviewTab({ form, callSheet }: PreviewTabProps) {
  const formData = form.watch()
  const title = formData.title || 'Call Sheet Preview'
  const shootDate = formData.shootDate ? new Date(formData.shootDate).toLocaleDateString() : 'TBD'
  const callTime = formData.callTime || 'TBD'
  const location = formData.location || 'TBD'
  // This is a mock preview - in production, this would generate an actual PDF preview
  return (
    <Card>
      <CardHeader>
        <CardTitle>Call Sheet Preview</CardTitle>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[600px] w-full rounded-md border p-8">
          <div className="space-y-6 max-w-2xl mx-auto">
            {/* Header */}
            <div className="text-center space-y-2">
              <h1 className="text-3xl font-bold">{title.toUpperCase()}</h1>
              <p className="text-lg">Call Sheet</p>
              <p className="text-muted-foreground">Monday, January 15, 2024</p>
            </div>

            {/* General Info */}
            <div className="border-t pt-4">
              <h2 className="text-xl font-semibold mb-3">General Information</h2>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <p className="font-semibold">Call Time:</p>
                  <p>7:00 AM</p>
                </div>
                <div>
                  <p className="font-semibold">Location:</p>
                  <p>123 Main Street, Los Angeles, CA</p>
                </div>
              </div>
            </div>

            {/* Schedule */}
            <div className="border-t pt-4">
              <h2 className="text-xl font-semibold mb-3">Schedule</h2>
              <div className="space-y-2">
                <div className="p-3 bg-gray-50 rounded">
                  <div className="flex justify-between items-center">
                    <p className="font-medium">Scene 1 - Opening Sequence</p>
                    <Badge variant="outline">8:00 AM</Badge>
                  </div>
                </div>
                <div className="p-3 bg-gray-50 rounded">
                  <div className="flex justify-between items-center">
                    <p className="font-medium">Scene 2 - Dialogue</p>
                    <Badge variant="outline">10:00 AM</Badge>
                  </div>
                </div>
              </div>
            </div>

            {/* Crew */}
            <div className="border-t pt-4">
              <h2 className="text-xl font-semibold mb-3">Crew & Cast</h2>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span>John Doe - Director</span>
                  <span className="text-muted-foreground">Direction</span>
                </div>
                <div className="flex justify-between">
                  <span>Jane Smith - Producer</span>
                  <span className="text-muted-foreground">Production</span>
                </div>
              </div>
            </div>

            {/* Notes */}
            <div className="border-t pt-4">
              <h2 className="text-xl font-semibold mb-3">Notes</h2>
              <div className="space-y-2 text-sm">
                <p>Please arrive 15 minutes before your call time.</p>
                <p>Parking available on site.</p>
              </div>
            </div>

            {/* Footer */}
            <div className="border-t pt-4 text-center text-sm text-muted-foreground">
              <p>Generated by Slate • Contact: production@example.com</p>
            </div>
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  )
}